### ISSUE TITLE
This shebang can call wrong python version...

### ISSUE THREAD

**Issue by Leslie-C** [Apb58/motif-mark#12]
...depending on user's environment.

https://github.com/Apb58/motif-mark/blob/ac6f76af537eab21122e9b6b37508fd31bc7478b/Motif_Marker.py#L1

Better shebang:
```/usr/bin/env python3```

**Comment by Apb58** [comment]
Updated; however, If I do this It will not run on my machine as my 3.6 environment is built through the anaconda, so I find this highly variable -- thus the reasoning in the README to adjust the shebang to your needs.
